name: CI - Verificador de Código

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analisar-codigo:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-node: '20'

    - name: Instalar e Rodar o Verificador de HTML/CSS
      run: |
        npm install --global htmlhint stylelint stylelint-config-standard
        npx htmlhint "**/*.html"
